package com.nazrul.model;
// Generated Apr 24, 2017 8:24:38 PM by Hibernate Tools 4.3.1



/**
 * Allowance generated by hbm2java
 */
public class Allowance  implements java.io.Serializable {


     private Integer id;
     private double overtime;
     private double medical;
     private double bonus;
     private double other;
     private int empId;
     private double salary;
     private double rate;
     private double totalAllowance;
     private String firstname;
     private String lastname;
     private String createdBy;
     private double totalOvertime;

    public Allowance() {
    }

    public Allowance(double overtime, double medical, double bonus, double other, int empId, double salary, double rate, double totalAllowance, String firstname, String lastname, String createdBy, double totalOvertime) {
       this.overtime = overtime;
       this.medical = medical;
       this.bonus = bonus;
       this.other = other;
       this.empId = empId;
       this.salary = salary;
       this.rate = rate;
       this.totalAllowance = totalAllowance;
       this.firstname = firstname;
       this.lastname = lastname;
       this.createdBy = createdBy;
       this.totalOvertime = totalOvertime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getOvertime() {
        return this.overtime;
    }
    
    public void setOvertime(double overtime) {
        this.overtime = overtime;
    }
    public double getMedical() {
        return this.medical;
    }
    
    public void setMedical(double medical) {
        this.medical = medical;
    }
    public double getBonus() {
        return this.bonus;
    }
    
    public void setBonus(double bonus) {
        this.bonus = bonus;
    }
    public double getOther() {
        return this.other;
    }
    
    public void setOther(double other) {
        this.other = other;
    }
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }
    public double getTotalAllowance() {
        return this.totalAllowance;
    }
    
    public void setTotalAllowance(double totalAllowance) {
        this.totalAllowance = totalAllowance;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public double getTotalOvertime() {
        return this.totalOvertime;
    }
    
    public void setTotalOvertime(double totalOvertime) {
        this.totalOvertime = totalOvertime;
    }




}


