package com.nazrul.model;
// Generated Apr 24, 2017 8:24:38 PM by Hibernate Tools 4.3.1



/**
 * Audit generated by hbm2java
 */
public class Audit  implements java.io.Serializable {


     private Integer auditId;
     private int empId;
     private String date;
     private String status;

    public Audit() {
    }

    public Audit(int empId, String date, String status) {
       this.empId = empId;
       this.date = date;
       this.status = status;
    }
   
    public Integer getAuditId() {
        return this.auditId;
    }
    
    public void setAuditId(Integer auditId) {
        this.auditId = auditId;
    }
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


