package com.nazrul.model;
// Generated Apr 24, 2017 8:24:38 PM by Hibernate Tools 4.3.1



/**
 * StaffInformation generated by hbm2java
 */
public class StaffInformation  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastname;
     private String dob;
     private String email;
     private String mobile;
     private String presentaddress;
     private String department;
     private byte[] image;
     private String gender;
     private double salary;
     private String permanentaddress;
     private String district;
     private String postCode;
     private String designation;
     private String status;
     private String dateHired;
     private String jobTitle;

    public StaffInformation() {
    }

    public StaffInformation(String firstName, String lastname, String dob, String email, String mobile, String presentaddress, String department, byte[] image, String gender, double salary, String permanentaddress, String district, String postCode, String designation, String status, String dateHired, String jobTitle) {
       this.firstName = firstName;
       this.lastname = lastname;
       this.dob = dob;
       this.email = email;
       this.mobile = mobile;
       this.presentaddress = presentaddress;
       this.department = department;
       this.image = image;
       this.gender = gender;
       this.salary = salary;
       this.permanentaddress = permanentaddress;
       this.district = district;
       this.postCode = postCode;
       this.designation = designation;
       this.status = status;
       this.dateHired = dateHired;
       this.jobTitle = jobTitle;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getPresentaddress() {
        return this.presentaddress;
    }
    
    public void setPresentaddress(String presentaddress) {
        this.presentaddress = presentaddress;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    public String getPermanentaddress() {
        return this.permanentaddress;
    }
    
    public void setPermanentaddress(String permanentaddress) {
        this.permanentaddress = permanentaddress;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDateHired() {
        return this.dateHired;
    }
    
    public void setDateHired(String dateHired) {
        this.dateHired = dateHired;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }


    public StaffInformation(Integer id, String firstName, String lastname, String dob, String department, double salary) {
        this.id = id;
        this.firstName = firstName;
        this.lastname = lastname;
        this.dob = dob;
        this.department = department;
        this.salary = salary;
    }

    public StaffInformation(Integer id, String firstName, String lastname, String dob, String email, String mobile, String presentaddress, String department, double salary, String permanentaddress, String district, String postCode, String designation, String status, String dateHired, String jobTitle) {
        this.id = id;
        this.firstName = firstName;
        this.lastname = lastname;
        this.dob = dob;
        this.email = email;
        this.mobile = mobile;
        this.presentaddress = presentaddress;
        this.department = department;
        this.salary = salary;
        this.permanentaddress = permanentaddress;
        this.district = district;
        this.postCode = postCode;
        this.designation = designation;
        this.status = status;
        this.dateHired = dateHired;
        this.jobTitle = jobTitle;
    }

   
    






}


